name: CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install deps
        run: pnpm install

      - name: Lint
        run: pnpm run lint

      - name: Test build
        run: pnpm run test